// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQ18mfgrqwsD4pRCc2_kwug2hldoUx9I',
    appId: '1:33366975385:web:d34b103966f166db2a6908',
    messagingSenderId: '33366975385',
    projectId: 'flutter-firebase-basics-bb333',
    authDomain: 'flutter-firebase-basics-bb333.firebaseapp.com',
    storageBucket: 'flutter-firebase-basics-bb333.appspot.com',
    measurementId: 'G-N9R23J0X73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpbxKKwadKRyy-LnhYhtM74eepYctSBU',
    appId: '1:33366975385:android:8be81af224d41b2a2a6908',
    messagingSenderId: '33366975385',
    projectId: 'flutter-firebase-basics-bb333',
    storageBucket: 'flutter-firebase-basics-bb333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8E43nRPnoWgr54hgZQHReMQxj2kVbpKs',
    appId: '1:33366975385:ios:e3f24b1f55fbe7b02a6908',
    messagingSenderId: '33366975385',
    projectId: 'flutter-firebase-basics-bb333',
    storageBucket: 'flutter-firebase-basics-bb333.appspot.com',
    iosBundleId: 'com.example.fbBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8E43nRPnoWgr54hgZQHReMQxj2kVbpKs',
    appId: '1:33366975385:ios:e3f24b1f55fbe7b02a6908',
    messagingSenderId: '33366975385',
    projectId: 'flutter-firebase-basics-bb333',
    storageBucket: 'flutter-firebase-basics-bb333.appspot.com',
    iosBundleId: 'com.example.fbBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkQ18mfgrqwsD4pRCc2_kwug2hldoUx9I',
    appId: '1:33366975385:web:814fed8a394280bf2a6908',
    messagingSenderId: '33366975385',
    projectId: 'flutter-firebase-basics-bb333',
    authDomain: 'flutter-firebase-basics-bb333.firebaseapp.com',
    storageBucket: 'flutter-firebase-basics-bb333.appspot.com',
    measurementId: 'G-X2BV3GKMWX',
  );
}
